squelch non-html label error from dot
The error message is

  $ dot -Tpdf -o sorting/select-sort/img/in-place-sort.pdf sorting/select-sort/img/in-place-sort.dot
  Warning: flat edge between adjacent nodes one of which has a record shape - replace records with HTML-like labels
    Edge sorted -> unsorted
  Error: lost sorted unsorted edge

Of course the actual error is harmless, since the edge in question is invisible anyway. But it's easy enough to squelch. See http://www.graphviz.org/doc/info/shapes.html which says "The record-based shape has largely been superseded ... consider using shape=none ...", and also has a nice example.